export const pricingTabs = [
  {
    id: 'webdesign',
    label: 'Web Design',
    cards: [
      {
        badge: 'Best Value',
        title: 'Startup Website Package',
        oldPrice: '$400 ONLY',
        price: '$159.00',
        features: [
          '1 to 3 Pages Website Design',
          '2 Stock Images',
          'Contact Forms',
          '5 Revisions',
          'Sliding Banner',
          'Portfolio & Pricing Section & Page',
          'Lifetime Support',
          'Complete Deployment',
          'Social Media Integration',
          'Complete Source Files',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '*NO MONTHLY OR ANY HIDDEN FEE*',
        ],
      },
      {
        badge: 'Popular',
        title: 'Professional Website Package',
        oldPrice: '$1000 ONLY',
        price: '$299.00',
        highlight: true,
        features: [
          '5 to 8 Pages Website Design',
          '5 Stock Images',
          'Contact Forms',
          '10 Revisions',
          'Sliding Banner',
          'Portfolio & Pricing Section & Page',
          'Lifetime Support',
          'Complete Deployment',
          'Social Media Integration',
          'Dedicated Project Manager',
          'Complete Source Files',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '*NO MONTHLY OR ANY HIDDEN FEE*',
        ],
      },
      {
        badge: 'Pro',
        title: 'Professional Web Design',
        sub: 'Custom design, advanced features, priority support.',
        oldPrice: '$2999',
        price: '$1499',
        features: [
          'Custom UX/UI design',
          'Unlimited pages & advanced CMS',
          'eCommerce / Multilingual support',
          'Performance & security hardening',
          'Integration with 3rd-party APIs',
          '1 year premium hosting & support',
          'Branding guidance',
        ],
      },
    ],
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce',
    cards: [
      {
        badge: 'Starter',
        title: 'Elite Website Package',
        oldPrice: '$1600 ONLY',
        price: '$459.00',
        features: [
          '10 to 15 Pages Website Design',
          '5 Stock Images',
          'Custom Dynamic Forms',
          '10 Revisions',
          'Sliding Banner',
          'Portfolio & Pricing Section & Page',
          'Lifetime Support',
          'Complete Deployment',
          'Social Media Integration',
          'Dedicated Project Manager',
          'Mobile Responsive',
          'Complete Source File',
          '100% Ownership Rights',
          '100% Satisfaction Guarantee',
          '100% Money Back Guarantee',
          '*NO MONTHLY OR ANY HIDDEN FEE*',
        ],
      },
      {
        badge: 'Scale',
        title: 'Startup E-Store',
        sub: 'Up to 100 products, SEO & marketing ready.',
        oldPrice: '$1598',
        price: '$799',
        highlight: true,
        features: [
          'Up to 100 products',
          'Advanced search & filters',
          'Coupons & discounts',
          'Multiple payment options',
          'Analytics integration',
          '6 months support',
        ],
      },
      {
        badge: 'Enterprise',
        title: 'Professional E-Store',
        sub: 'Large catalog, advanced features & automation.',
        oldPrice: '$2798',
        price: '$1399',
        features: [
          'Up to 500+ products',
          'Full shopping cart & inventory',
          'Product reviews & ratings',
          'Automated emails & order flows',
          'Performance & security package',
          'Priority support',
        ],
      },
    ],
  },
  {
    id: 'logo',
    label: 'Logo Design',
    cards: [
      {
        badge: 'Simple',
        title: 'Basic Logo',
        sub: '2 concepts, fast delivery.',
        oldPrice: '$199',
        price: '$99',
        features: ['2 logo concepts', '2 revisions', 'PNG + JPEG delivery', '48 hours delivery'],
      },
      {
        badge: 'Brand',
        title: 'Startup Logo Pack',
        sub: '5 concepts, full files.',
        oldPrice: '$499',
        price: '$249',
        highlight: true,
        features: ['5 concepts', 'Unlimited revisions', 'AI + PSD + Vector', 'Stationery mockup'],
      },
      {
        badge: 'Pro',
        title: 'Professional Brand',
        sub: 'Brand guide + many files.',
        oldPrice: '$899',
        price: '$499',
        features: ['10+ logo concepts', 'Brand guidelines', 'All vector & raster files', 'Dedicated designer'],
      },
    ],
  },
];
